In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [19]:
pd.set_option('display.max_columns', 101)
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header=None)
# print(df)
df = df.replace(99.00, np.NaN)
df = df.iloc[:,1:]
print(df)

        1     2     3     4     5     6     7     8     9     10    11    12   \
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76 -8.50 -6.75   
1      4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  6.75  8.64   
2       NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN   NaN  7.33  7.57   
3       NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  1.84  7.33  6.60   
4      8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  8.25  6.84   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
24978  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  7.23 -0.53  5.63   
24979  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  4.90  8.88 -8.69   
24980   NaN   NaN   NaN   NaN -7.77   NaN  6.70 -6.75   NaN   NaN   NaN   NaN   
24981   NaN   NaN   NaN   NaN -9.71   NaN  4.56 -8.30   NaN   NaN   NaN   NaN   
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  4.61 -3.16  7.38   

        13    14    15    1

In [32]:
pd.set_option('display.max_columns', 101)
pd.set_option('display.max_rows', 101)

df.mean()

1      0.904573
2      0.208460
3      0.316574
4     -1.449114
5      0.403556
6      1.594447
7     -0.429662
8     -0.624085
9     -0.557031
10     1.301231
11     1.805797
12     1.449290
13    -1.762882
14     1.396334
15    -1.706201
16    -3.104818
17    -1.115141
18    -0.635103
19     0.154227
20    -0.933997
21     2.095626
22     0.868662
23     0.109192
24    -1.687420
25     0.382373
26     1.286232
27     3.189821
28     1.518830
29     2.972455
30    -0.436493
31     2.198943
32     3.155988
33    -1.368648
34     0.859494
35     3.006351
36     3.312500
37    -1.363987
38     1.300479
39     1.067337
40     0.998635
41    -0.320500
42     1.966875
43    -0.924856
44    -2.111891
45     1.108616
46     1.500232
47     1.559535
48     1.825884
49     2.771298
50     3.665085
51    -0.731653
52    -0.133121
53     2.939463
54     2.735697
55     0.505731
56     1.764647
57    -1.990664
58    -3.833880
59    -0.578010
60    -0.325394
61     2.459180
62     2.976021
63     0

In [35]:
df.iloc[22189, 37]

3.4

In [5]:
import numpy as np


def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        
        ### YOUR CODE (inner loop) HERE
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating) and rating!=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print('Iteration %d/%d:    MSE=%.3f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [6]:
sgd(100)

NameError: name 'latent_user_preferences' is not defined

In [20]:
arr = df.values
print(arr.shape)

(24983, 100)


In [21]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)


In [22]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
#   rated = np.where(arr!=99)
  rated = np.where(arr!=np.NaN)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99.00
  return new_data, (rated[0][idx], rated[1][idx])


In [23]:
new_arr, idx = replace(arr, 0.1)

In [24]:
new_arr

array([[99.  ,  8.79, -9.66, ...,   nan, 99.  ,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan, 99.  ,   nan, ..., 99.  ,   nan,   nan],
       [99.  ,   nan, 99.  , ...,   nan,   nan, 99.  ],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [25]:
idx

(array([16832,  4276, 18352, ..., 15841, 17121,  1211]),
 array([ 8, 26, 58, ..., 72, 46, 92]))

In [ ]:

arr[idx[0][0], idx[1][0]]

In [ ]:
new_arr[idx[0][0], idx[1][0]]